# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newapiel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://newcontain2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d83b52d98fee4b5494ed36cef033a0b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3ba9d55a01cf4b52b177a853ce0e566a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: newcontain2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d83b52d98fee4b5494ed36cef033a0b7 }}/newdockgitactapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newapiel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9738e77ebc44dfaac3c71399956d3f4 }}
        images: 'newcontain2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d83b52d98fee4b5494ed36cef033a0b7 }}/newdockgitactapi:${{ github.sha }}'